import { type NextPage } from "next";
import Head from "next/head";
import { HelpWidget } from "../components/HelpWidget";
// import Link from "next/link";

// import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-end justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] p-10">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
        </div>
        <HelpWidget />
      </main>
    </>
  );
};

export default Home;
